### ISSUE TITLE
Still trying to connect to V2 onions

### ISSUE THREAD

**Issue by rex4539** [ZeroNetX/ZeroNet#125]
`zeronet-enhanced` branch

Still trying to connect to V2 onions although they are deprecated.

```
Site:1NAMEz..qDNv [FAILED] ydy3wyg7m7t27ley.onion:15441: None
Site:1NAMEz..qDNv [FAILED] 3ccn46gztcvr2obl.onion:15441: None
Site:1NAMEz..qDNv [FAILED] fkzlfepq22b2mqwo.onion:15441: None
Site:1NAMEz..qDNv [FAILED] wyupyupgzdqcr5zb.onion:15441: None
Site:1NAMEz..qDNv [FAILED] ypqh67oe47phfsym.onion:15441: None
Site:1NAMEz..qDNv [FAILED] lfcjxynq7efainwm.onion:29843: None
Site:1NAMEz..qDNv [FAILED] neklnbzzmxzjezmj.onion:15441: None
Site:1NAMEz..qDNv [FAILED] aitiin3f5naetmut.onion:21532: None
Site:1NAMEz..qDNv [FAILED] mitofl3jvuqgabts.onion:35697: None
Site:1NAMEz..qDNv [FAILED] zfzulm23jbonywl4.onion:14896: None
Site:1NAMEz..qDNv [FAILED] xeegbt7osfrpgyet.onion:15441: None
Site:1iD5ZQ..duGz [FAILED] l3lz3o3nijc2i42r.onion:35938: None
Site:1iD5ZQ..duGz [FAILED] s6nkpy5uhb7j4kcy.onion:19039: None
Site:1iD5ZQ..duGz [FAILED] rnoen6jdrkedfjsm.onion:13495: None
Site:1iD5ZQ..duGz [FAILED] 7spgxr4kflqkyos4.onion:15441: None
Site:1iD5ZQ..duGz [FAILED] hk3nvoefun5fjaxf.onion:15441: None
Site:1iD5ZQ..duGz [FAILED] uqhbe2hz2z4k7adt.onion:23491: None
```

**Comment by caryoscelus** [comment]
my node successfully connects to v2 onions . as far as i understand , it depends on whether you use tor-browser as your tor proxy or tor daemon itself

**Comment by rex4539** [comment]
I use Tor Browser with tor always enabled, plus I run the tor service separately (which is latest master).

The fact that it failed is expected, since my tor service doesn't support V2 onions but I was under the impression that V2 is deprecated and insecure so ZeroNet should not even try to connect to such addresses.

**Comment by caryoscelus** [comment]
> V2 is deprecated

that's true , it was deprecated by the tor project

> and insecure

it's been used for years without much issues . v3 is purported to be more secure , but it doesn't render v2 strictly insecure

> so ZeroNet should not even try to connect to such addresses.

ZeroNet is dead and only supports v2 . some of the forks with v3 support may elect to disable v2 support , but e.g. my fork is going to support it until there's a good reason to drop it (such as there are no v2-only nodes anymore) . i don't want to discourage people who haven't updated because of the fork situation and intimidate them into deciding what fork to use

**Comment by canewsin** [comment]
those addresses might be non working onion addresses recently updated to v3 clients, in bittorrent tracker systems, we can't estimate whether address is reachable or not until tracker believes that client is non responded and remove it from its database, this may take some time, errors are common in coming days because those v2 addresses are exist from long time and may have higher reputation in tracker DB.

**Comment by slrslr** [comment]
Same as caryoscelus my ZNX enhanced can connect V2 onion:
`INFO     Site:1NAMEz..qDNv [OK] ctaa6r7ewdux4ahn.onion:15441: Thanks, file data/issuers/1M2XsD13r7opv2n1Akucd8LdPMAAhYXCwL/content.json updated! 11/6`

possibly issue on @rex4539 side not an issue in ZNX enhanced i think
